POST http://localhost:3000/api/qrcodes/
Content-Type: application/json

{
    "title": "코드잇 커뮤니티",
    "url": "https://www.codeit.kr/community/general"
}

###

GET http://localhost:3000/api/qrcodes/

###

GET http://localhost:3000/api/qrcodes/67c85158e67d3cd0bb5e1a33

###

PATCH  http://localhost:3000/api/qrcodes/67c85158e67d3cd0bb5e1a33
Content-Type: application/json

{
    "title": "코드잇 커뮤니티!"
}

###

DELETE http://localhost:3000/api/qrcodes/67c85158e67d3cd0bb5e1a33